### ISSUE TITLE
Set limits on when flat-fielding can take place

### ISSUE THREAD

**Issue by wtgee** [AstroHuntsman/POCS#17]
Set up some kind of limit, probably based off sun position, for evening and potential morning flat-fields.

**Comment by AnthonyHorton** [comment]
Probably something as simple as min and max Sun altitude would do, plus weather constraints (twilight flats taken in non-photometric conditions are unlikely to be much use).

**Comment by wtgee** [comment]
My plan was to set min=0 and max=-18 (or is that min/max the other way around?) and only attempt during those times. 

I'm actually going to go up and test the flat-fielding tonight.

**Comment by AnthonyHorton** [comment]
Great! 0 to -18 degrees is a good starting point which we can then narrow down experimentally. We might want to define suitable ranges individually for different filters, etc., as well as the overall range which is used to enter/exit the flat fielding state.

**Comment by lspitler** [comment]
Tonight we found out:

~20 minutes after sunset in altaz direction of 50,50 Halpha starts out at ~9s @ ~9000 counts and nearly completes 10 exposures before it gets too faint
